spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/aggregator
            - classpath:config/telemetry/analyzer
            - classpath:config/telemetry/collector
            - classpath:config/commerce/shopping-store
            - classpath:config/commerce/shopping-cart
            - classpath:config/commerce/warehouse
            - classpath:config/commerce/order
            - classpath:config/commerce/payment
            - classpath:config/commerce/delivery
            - classpath:config/infra/gateway
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/