spring:
  kafka:
    bootstrap-servers: localhost:9092

    grpc-producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      schema-registry-url: http://localhost:8081

    byte-producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

collector:
  topic:
    telemetry:
      sensors:
        v1: telemetry.sensors.v1
      snapshots:
        v1: telemetry.snapshots.v1
      hubs:
        v1: telemetry.hubs.v1

grpc:
  server:
  port: 9090