spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.AvroSerializer
collector:
  topic:
    telemetry:
      sensors:
        v1: telemetry.sensors.v1
      snapshots:
        v1: telemetry.snapshots.v1
      hubs:
        v1: telemetry.hubs.v1

grpc:
  server:
    port: 59091